### ISSUE TITLE
Can not convert to fp16 using llama.cpp

### ISSUE THREAD

**Issue by ngdnghia28** [VinAIResearch/PhoGPT#24]
I use llama.cpp to convert pytorch model to fp16.
Follow is the error.

```
python3 convert.py ../PhoGPT-4B-Chat --outtype f16 --outfile ../phogpt-4b-chat.fp16.bin
Loading model file ../PhoGPT-4B-Chat/pytorch_model.bin
Traceback (most recent call last):
  File "/Users/***/temp/llama.cpp/convert.py", line 1479, in <module>
    main()
  File "/Users/***/temp/llama.cpp/convert.py", line 1426, in main
    params = Params.load(model_plus)
  File "/Users/***/temp/llama.cpp/convert.py", line 317, in load
    params = Params.loadHFTransformerJson(model_plus.model, hf_config_path)
  File "/Users/***/temp/llama.cpp/convert.py", line 236, in loadHFTransformerJson
    raise Exception("failed to guess 'n_ctx'. This model is unknown or unsupported.\n"
Exception: failed to guess 'n_ctx'. This model is unknown or unsupported.
Suggestion: provide 'config.json' of the model in the same directory containing model files.
```

**Comment by ngdnghia28** [comment]
Use this instead
`python3 convert-hf-to-gguf.py ~/.models/PhoGPT-4B-Chat --outfile ~/.models/pho.gguf`
